Repository liquibase/node-liquibase, pull requests merged in 2021-05, with the labels that each got.

#23 [22] - Tag function adds additional command parameter including comma…
  package.json
  src/enums/commands-with-positional-arguments.ts
  src/liquibase.ts
  src/models/commands/update-command-attributes.model.ts
  src/models/liquibase-config.model.ts
Labels: bug, enhancement

#24 create github actions CI
  .github/workflows/node.js.yml
  old.travis.yml
Labels: enhancement

#27 20
  package.json
  src/liquibase.ts
  src/util/command-handler.spec.ts
  src/util/command-handler.ts
  src/util/logger.spec.ts
  src/util/logger.ts
Labels: bug

#29 fix(jsdoc): fixed JSDoc example for `Liquibase`.
  src/liquibase.ts
Labels: documentation, enhancement

#30 issue 28
  .eslintrc.js
  .github/workflows/node.js.yml
  package.json
  src/cli.ts
  src/constants/defaults/mssql-default.config.ts
  src/constants/defaults/postgresql-default.config.ts
  src/enums/commands-with-positional-arguments.ts
  src/enums/liquibase-log-levels.enum.ts
  src/index.ts
  src/liquibase.spec.ts
  src/liquibase.ts
  src/models/commands/changelog-sync-to-tag-command-attributes.model.ts
  src/models/commands/changelog-sync-to-tag-sql-command-attributes.model.ts
  src/models/commands/db-doc-command-attributes.model.ts
  src/models/commands/diff-changelog-command-attributes.model.ts
  src/models/commands/diff-command-attributes.model.ts
  src/models/commands/future-rollback-count-sql-command-attributes.model.ts
  src/models/commands/generate-changelog-command-attributes.model.ts
  src/models/commands/index.ts
  src/models/commands/rollback-command-attributes.model.ts
  src/models/commands/rollback-count-command-attributes.model.ts
  src/models/commands/rollback-count-sql-command-attributes.model.ts
  src/models/commands/rollback-sql-command-attributes.model.ts
  src/models/commands/rollback-to-date-command-attributes.model.ts
  src/models/commands/rollback-to-date-sql-command-attributes.model.ts
  src/models/commands/snapshot-command-attributes.model.ts
  src/models/commands/snapshot-reference-command-attributes.model.ts
  src/models/commands/sync-hub-command-attributes.model.ts
  src/models/commands/tag-command-attributes.model.ts
  src/models/commands/tag-exists-command-attributes.model.ts
  src/models/liquibase-config.model.ts
  src/util/command-handler.spec.ts
  src/util/command-handler.ts
  src/util/file-helper.spec.ts
  src/util/file-helper.ts
  src/util/logger.spec.ts
  src/util/logger.ts
Labels: bug
